### ISSUE TITLE
What is the correct description for a supernumerary chromosome?

### ISSUE THREAD

**Issue by ifokkema** [HGVSnomenclature/hgvs-nomenclature#153]
The HGVS nomenclature explains two ways to describe supernumerary chromosomes.

With square brackets:
> the description of the supernumerary molecule is given using "[ ]sup".

([source](https://hgvs-nomenclature.org/stable/recommendations/DNA/complex/))

or, without:
> `NC_000023.11:g.pter_qtersup`

([source](https://hgvs-nomenclature.org/stable/recommendations/DNA/duplication/))

I have just received data where the description `NC_000023.10:g.[pter_qter]sup` is given, and I can't tell whether that's correct or not.

**Comment by jfjlaros** [comment]
My few cents.

I would like the operators to have as few meanings as possible. Since the `[]` is already used to group variants into alleles and as a counter in repeats, I would advise against mandating yet another use (as a reading aid).

I am aware that this is already being used when inserting slices of foreign reference sequences, there I would also like to see it as an optional reading aid.

**Comment by jtdendunnen** [comment]
Ivo, as far as I know NC_000023.10:g.[pter_qter]sup is not correct. the current recommendation is to use NC_000023.10:g.pter_qtersup.
